# Generated by Django 4.0.5 on 2022-06-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('nombres', models.CharField(max_length=40)),
                ('apePaterno', models.CharField(max_length=40)),
                ('apeMaterno', models.CharField(max_length=40)),
                ('nacimiento', models.DateField()),
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('cui', models.CharField(max_length=8)),
            ],
        ),
    ]
