# Generated by Django 4.0.5 on 2022-06-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_alter_persona_donador_alter_persona_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='donador',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
